### ISSUE TITLE
alsa.c:149:16: error: ‘return’ with a value, in function returning void [-Wreturn-mismatch]

### ISSUE THREAD

**Issue by RAMChYLD** [tiwai/awesfx#3]
Awesfx no longer compiles on GCC14. 

Attempt to compile results in the following error: 
`alsa.c:149:16: error: ‘return’ with a value, in function returning void [-Wreturn-mismatch]`

I assume this is because GCC13 and below were lenient enough to allow this, but GCC14 isn't. 

Patch to fix issue attached. All I did was change void to int as with the other functions in the class. 
[set_gus_bank_fix.patch.txt](https://github.com/tiwai/awesfx/files/15369415/set_gus_bank_fix.patch.txt)

**Comment by tiwai** [comment]
Already fixed in git repo, commit 682d0caaffa9bfcc2381b947fb47395fb3da98b9
